export enum _EEdgeMethod {
    VISIBLE = 'visible',
    HIDDEN = 'hidden'
}
export enum _EMeshMethod {
    FACETED = 'faceted',
    SMOOTH = 'smooth'
}
// https://codesandbox.io/s/5w573r54w4
export enum _EColorRampMethod {
    FALSE_COLOR = 'false_color',
    BLACK_BODY = 'black_body',
    WHITE_RED = 'white_red',
    WHITE_GREEN = 'white_green',
    WHITE_BLUE = 'white_blue',
    BLUE_RED = 'blue_red',
    GREEN_RED = 'green_red',
    BLUE_GREEN = 'blue_green',
    GREY_SCALE = 'grey_scale',
    ORRD= 'OrRd',
    PUBU= 'PuBu',
    BUPU= 'BuPu',
    ORANGES= 'Oranges',
    BUGN= 'BuGn',
    YLORBR= 'YlOrBr',
    YLGN= 'YlGn',
    REDS= 'Reds',
    RDPU= 'RdPu',
    GREENS= 'Greens',
    YLGNBU= 'YlGnBu',
    PURPLES= 'Purples',
    GNBU= 'GnBu',
    GREYS= 'Greys',
    YLORRD= 'YlOrRd',
    PURD= 'PuRd',
    BLUES= 'Blues',
    PUBUGN= 'PuBuGn',
    VIRIDIS= 'Viridis',
    SPECTRAL= 'Spectral',
    RDYLGN= 'RdYlGn',
    RDBU= 'RdBu',
    PIYG= 'PiYG',
    PRGN= 'PRGn',
    RDYLBU= 'RdYlBu',
    BRBG= 'BrBG',
    RDGY= 'RdGy',
    PUOR= 'PuOr',
    SET2= 'Set2',
    ACCENT= 'Accent',
    SET1= 'Set1',
    SET3= 'Set3',
    DARK2= 'Dark2',
    PAIRED= 'Paired',
    PASTEL2= 'Pastel2',
    PASTEL1= 'Pastel1',
}
